import {
  BrainCircuit,
  Camera,
  Check,
  CornerDownLeft,
  Database,
  FileText,
  FolderTree,
  Minimize2,
  Search,
  Sparkles,
  Wrench,
  Zap,
} from 'lucide-react';
export const actionIcons: Record<string, typeof Search> = {
  analyzing: Zap,
  clarify: BrainCircuit,
  clarifyResponse: Check,
  compressing: Minimize2,
  generate: Sparkles,
  generating: Sparkles,
  ls: FolderTree,
  readFile: FileText,
  retrieved: Database,
  screenshot: Camera,
  search: Search,
  searching: Search,
  steer: CornerDownLeft,
  toolCall: Wrench,
};
